/**
 * useDtmfTones Hook - Generate DTMF touch tones using Web Audio API
 * Server path: /opt/irontec/ivozprovider/web/portal/client/src/hooks/useDtmfTones.ts
 * Server: vm-ivozprovider-lab (185.16.41.36)
 * Last updated: 2026-01-27
 *
 * DTMF (Dual-Tone Multi-Frequency) tones are generated by combining
 * two sine waves - one from the low frequency group and one from the high.
 */

import { useCallback, useRef } from 'react';

// DTMF frequency matrix
// Each digit is the combination of a row frequency and column frequency
const LOW_FREQUENCIES: Record<string, number> = {
  '1': 697, '2': 697, '3': 697,
  '4': 770, '5': 770, '6': 770,
  '7': 852, '8': 852, '9': 852,
  '*': 941, '0': 941, '#': 941,
};

const HIGH_FREQUENCIES: Record<string, number> = {
  '1': 1209, '2': 1336, '3': 1477,
  '4': 1209, '5': 1336, '6': 1477,
  '7': 1209, '8': 1336, '9': 1477,
  '*': 1209, '0': 1336, '#': 1477,
};

// Default tone duration in milliseconds
const DEFAULT_DURATION_MS = 150;

// Default volume (0.0 to 1.0)
const DEFAULT_VOLUME = 0.3;

interface UseDtmfTonesReturn {
  playTone: (digit: string, durationMs?: number) => void;
}

export const useDtmfTones = (volume: number = DEFAULT_VOLUME): UseDtmfTonesReturn => {
  // Singleton AudioContext - created on first use
  const audioContextRef = useRef<AudioContext | null>(null);

  const getAudioContext = useCallback((): AudioContext | null => {
    // Create AudioContext lazily (browsers require user interaction first)
    if (!audioContextRef.current) {
      try {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
      } catch (e) {
        console.warn('[DTMF] Web Audio API not supported:', e);
        return null;
      }
    }

    // Resume if suspended (browsers suspend AudioContext until user interaction)
    if (audioContextRef.current.state === 'suspended') {
      audioContextRef.current.resume();
    }

    return audioContextRef.current;
  }, []);

  const playTone = useCallback(
    (digit: string, durationMs: number = DEFAULT_DURATION_MS) => {
      const lowFreq = LOW_FREQUENCIES[digit];
      const highFreq = HIGH_FREQUENCIES[digit];

      if (!lowFreq || !highFreq) {
        // Unknown digit, skip
        return;
      }

      const audioContext = getAudioContext();
      if (!audioContext) {
        return;
      }

      const now = audioContext.currentTime;
      const duration = durationMs / 1000; // Convert to seconds

      // Create gain node for volume control and fade out
      const gainNode = audioContext.createGain();
      gainNode.connect(audioContext.destination);
      gainNode.gain.setValueAtTime(volume, now);
      // Fade out at the end to prevent click
      gainNode.gain.exponentialRampToValueAtTime(0.001, now + duration);

      // Create low frequency oscillator
      const lowOsc = audioContext.createOscillator();
      lowOsc.type = 'sine';
      lowOsc.frequency.setValueAtTime(lowFreq, now);
      lowOsc.connect(gainNode);

      // Create high frequency oscillator
      const highOsc = audioContext.createOscillator();
      highOsc.type = 'sine';
      highOsc.frequency.setValueAtTime(highFreq, now);
      highOsc.connect(gainNode);

      // Start and stop oscillators
      lowOsc.start(now);
      highOsc.start(now);
      lowOsc.stop(now + duration);
      highOsc.stop(now + duration);
    },
    [getAudioContext, volume]
  );

  return { playTone };
};

export default useDtmfTones;
